### ISSUE TITLE
Migrate to null-safety

### ISSUE THREAD

**Issue by Ch4rl3B** [sanilch99/excel_to_anything#2]
Please migrate to null-safety. This package rocks, if you want I can make it and do a pull request

**Comment by sanilch99** [comment]
Hi @Ch4rl3B , its been on my checklist for a while to migrate this to null safety , but i couldnt get the time to do it due to uni exams, if you can migrate it , might as well create a pull request, it would be great :+1:

**Comment by Ch4rl3B** [comment]
@sanilch99 I've made a pull request solving the issue 
#3

**Comment by sanilch99** [comment]
Succesfully migrated to null-safety , all kudos to @Ch4rl3B 
#3
